#basic workflow
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [main]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    
  steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    
    - name : run a script
      run: echo hello world
    - name: run a multi-line script
      run: 
        echo add other things,
        echo test.
    

     

    
